# Generated by Django 4.2.4 on 2023-08-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvseries',
            name='img',
            field=models.ImageField(default='abc', upload_to='picture'),
            preserve_default=False,
        ),
    ]
